version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: service_proxy
    ports:
      - 8080:8080
    volumes:
      - ./service_proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - koterpnetwork
  usersservices:
    build: ./users_services/
    container_name: koterp_usersservices
    ports:
      - 9021:9021
    networks:
      - koterpnetwork
    environment:
      - NODE_ENV=production
      - SERVICE_NAME="users_services"
      - APP_PORT=9021
      - APP_HOSTNAME=0.0.0.0
      - LOGGER_ENABLED=false
      - LOGGER_LEVEL="info"
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=koterp
      - DB_HOST=koterpdatabase
  
  providersservices:
    build: ./providers_services/
    container_name: koterp_providersservices
    ports:
      - 9022:9022
    networks:
      - koterpnetwork
    environment:
      - NODE_ENV=production
      - SERVICE_NAME="providers_services"
      - APP_PORT=9022
      - APP_HOSTNAME=0.0.0.0
      - LOGGER_ENABLED=false
      - LOGGER_LEVEL="info"
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=koterp
      - DB_HOST=koterpdatabase
  
  customersservices:
    build: ./customers_services/
    container_name: koterp_customersservices
    ports:
      - 9023:9023
    networks:
      - koterpnetwork
    environment:
      - NODE_ENV=production
      - SERVICE_NAME="customers_services"
      - APP_PORT=9023
      - APP_HOSTNAME=0.0.0.0
      - LOGGER_ENABLED=false
      - LOGGER_LEVEL="info"
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=koterp
      - DB_HOST=koterpdatabase

  productsservices:
    build: ./products_services/
    container_name: koterp_productsservices
    ports:
      - 9024:9024
    networks:
      - koterpnetwork
    environment:
      - NODE_ENV=production
      - SERVICE_NAME="products_services"
      - APP_PORT=9024
      - APP_HOSTNAME=0.0.0.0
      - LOGGER_ENABLED=false
      - LOGGER_LEVEL="info"
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=koterp
      - DB_HOST=koterpdatabase

networks:
  koterpnetwork:
    external: true
  